version: '3.8'

services:
  mongo:
    image: mongo:4
    restart: always

  mongoexpress:
    image: mongo-express
    ports:
      - "8082:8082"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:exercise2024@exercise_execisedb:27017
      - ME_CONFIG_BASICAUTH_USERNAME=exercise
      - ME_CONFIG_BASICAUTH_PASSWORD=exercise2024
      - ME_CONFIG_BASICAUTH=true
    depends_on:
      - mongo
    restart: always
